Repository mattermost/mattermost-handbook, pull requests merged in 2020-04, with the labels that each got.

#78 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 1: SME Review

#124 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 3: Reviews Complete

#126 Updates to publishing AORs
  operations/operations/publishing/web-properties.md
Labels: 3: Reviews Complete

#66 Update how-to-create-release-announcements.md
  .gitbook/assets/screenshot_guidelines.png
  .gitbook/assets/screenshot_guidelines2.png
  .gitbook/assets/screenshot_guidelines3.png
  .gitbook/assets/screenshot_guidelines4.png
  .gitbook/assets/screenshot_guidelines5.png
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
Labels: 3: Reviews Complete

#67 Update business-travel-insurance.md
  operations/workplace/people/working-at-mattermost/travel/business-travel-insurance.md
Labels: 3: Reviews Complete

#90 Create writing-an-mvp.md
  SUMMARY.md
  operations/operations/publishing/publishing-guidelines/writing-an-mvp.md
Labels: 3: Reviews Complete

#98 WIP: Product planning documentation
  SUMMARY.md
  operations/research-and-development/product/product-planning/README.md
  operations/research-and-development/product/product-planning/feature-requests.md
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
  operations/research-and-development/product/product-planning/launch-plan.md
  operations/research-and-development/product/product-planning/prioritization-process.md
  operations/research-and-development/product/product-planning/product-philosophy-and-principles.md
  operations/research-and-development/product/product-planning/release-plan.md
  operations/research-and-development/product/product-planning/release-planning-process.md
  operations/research-and-development/product/product-planning/roadmap-views.md
  operations/research-and-development/product/product-roadmap-cadence.md
Labels: 3: Reviews Complete

#131 Update onboarding/README.md
  contributors/onboarding/README.md
Labels: 3: Reviews Complete

#133 Minor formatting update to 'how to update handbook'
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#135 Update how-to-use-productboard.md
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 3: Reviews Complete

#140 Update link in How to use Expensify section
  company/how-to-guides-for-staff/how-to-spend-company-money/how-to-use-expensify.md
Labels: 3: Reviews Complete

#103 Adding new section: Documentation style guide
  SUMMARY.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#142 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 3: Reviews Complete

#141 Rename writing-an-mvp.md to submitting-documentation-with-your-PR.md
  operations/operations/publishing/publishing-guidelines/submitting-documentation-with-your-PR.md
Labels: 3: Reviews Complete

#143 Update SUMMARY.md > new TOC link
  SUMMARY.md
Labels: 2: Editor Review

#137 Expensify Reimbursement Policy
  company/how-to-guides-for-staff/how-to-spend-company-money/how-to-use-expensify.md
Labels: 3: Reviews Complete

#138 Update leaves-of-absence/README.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/README.md
Labels: 3: Reviews Complete

#136 Update to ROW section and Payment Facilities
  company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/how-to-get-paid.md
Labels: 3: Reviews Complete

#134 Update paid-time-off.md
  operations/workplace/people/working-at-mattermost/paid-time-off.md
Labels: 3: Reviews Complete

#139 Update onboarding.README.md
  contributors/onboarding/README.md
Labels: 3: Reviews Complete

#150 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#130 Update how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
Labels: 3: Reviews Complete

#112 Update README.md
  operations/workplace/README.md
Labels: 3: Reviews Complete

#152 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#155 Add files via upload to rectify broken image in tech writing handbook
  .gitbook/assets/Screen Shot 2020-04-18 at 12.56.26.png
Labels: 1: SME Review

#157 Update onboarding/README.md
  contributors/onboarding/README.md
Labels: 3: Reviews Complete

#156 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 2: Editor Review

#158 Add screenshot to illustrate Doc Up plugin
  .gitbook/assets/doc-up-plugin.png
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#160 Move PM hiring process to the handbook
  SUMMARY.md
  contributors/join-us/staff-recruiting/README.md
  contributors/join-us/staff-recruiting/product-manager-hiring.md
Labels: 3: Reviews Complete

#161 Update dashboards.md
  operations/business-operations/analytics/looker/dashboards.md
Labels: 1: SME Review

#163 Update README.md
  operations/customer-success/README.md
Labels: 1: SME Review

#162 Delete analytics.md
  operations/customer-success/analytics.md
Labels: 1: SME Review, 3: Reviews Complete

#165 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#169 Update customer-support.md
  .gitbook/assets/Support team image for handbook.PNG
  operations/business-operations/customer-support.md
Labels: 3: Reviews Complete

#170 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 3: Reviews Complete

#171 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 3: Reviews Complete

#174 Updates to CEO listening tour page
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#175 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#159 Move release process docs to handbook
  operations/research-and-development/product/release-process/README.md
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/dot-release.md
  operations/research-and-development/product/release-process/feature-release.md
  operations/research-and-development/product/release-process/mobile-release.md
  operations/research-and-development/product/release-process/release-overview.md
  operations/research-and-development/product/release-process/release-scorecard-definitions.md
  operations/research-and-development/product/release-process/release-tips.md
  operations/research-and-development/product/release-process/security-release.md
Labels: 3: Reviews Complete

#176 Add release process to TOC
  SUMMARY.md
Labels: 3: Reviews Complete

#177 Link updates to release docs
  operations/research-and-development/product/release-process/release-overview.md
  operations/research-and-development/product/release-process/release-tips.md
Labels: 3: Reviews Complete

#172 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 1: SME Review

#182 Add files via upload
  .gitbook/assets/Escalation_Process.png
  .gitbook/assets/Support_Process_Workflow.png
Labels: 2: Editor Review

#179 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 1: SME Review, 2: Editor Review

#185 Update metrics-definitions.md
  operations/business-operations/analytics/metrics-definitions.md
Labels: 3: Reviews Complete

#187 Migrate development process to new handbook
  SUMMARY.md
  operations/research-and-development/product/development-process/README.md
  operations/research-and-development/product/development-process/bug-severity-guidelines.md
  operations/research-and-development/product/development-process/deprecated-features.md
  operations/research-and-development/product/development-process/new-bug-tickets.md
  operations/research-and-development/product/development-process/software-requirements.md
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#193 Update to CEO listening tour docs
  operations/operations/company-cadence.md
Labels: 2: Editor Review

#194 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 1: SME Review
