Repository mattermost/mattermost-handbook, pull requests merged in 2020-05, with the labels that each got.

#196 Migrate 'how to run a hackathon' to handbook
  SUMMARY.md
  contributors/contributors/how-to-run-a-hackathon.md
Labels: 3: Reviews Complete

#186 Updates to PM team handbook
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#200 Update new-staff-performance-review.md
  operations/workplace/people/performance-reviews-50/new-staff-performance-review.md
Labels: 3: Reviews Complete

#190 Update feature-release.md
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#201 Update AORs for product documentation
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#204 Update Nerfs and Buffs
  company/about-mattermost/list-of-terms.md
Labels: 3: Reviews Complete

#151 Added CE section
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#205 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#198 Add engineering onboarding doc to handbook, small organizational changes to onboarding section of handbook
  SUMMARY.md
  contributors/onboarding/README.md
  contributors/onboarding/onboarding.md
  contributors/onboarding/r-and-d-onboarding.md
  contributors/onboarding/staff-onboarding-guide/README.md
  contributors/onboarding/staff-onboarding-guide/engineer-onboarding.md
Labels: 3: Reviews Complete

#207 Update how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
Labels: 3: Reviews Complete

#208 Update README.md
  operations/workplace/people/README.md
Labels: 3: Reviews Complete

#209 Update new-staff-performance-review.md
  operations/workplace/people/performance-reviews-50/new-staff-performance-review.md
Labels: 3: Reviews Complete

#195 Complete "community overview" page migration to handboock
  contributors/contributors/community.md
Labels: 3: Reviews Complete

#211 Add files via upload
  .gitbook/assets/Sales_Support_Process_Workflow.png
Labels: 3: Reviews Complete

#189 Migrate integrations directory update process to handbook, create 'how to' section for product
  SUMMARY.md
  operations/research-and-development/product/how-to-guides-for-product/README.md
  operations/research-and-development/product/how-to-guides-for-product/integrations-directory.md
Labels: 3: Reviews Complete

#215 Renewal Definitions
  .gitbook/assets/renewal_metrics_handbook.png
  operations/business-operations/analytics/metrics-definitions.md
Labels: 1: SME Review, 2: Editor Review

#214 Create help-wanted doc in new handbook
  SUMMARY.md
  contributors/contributors/help-wanted.md
Labels: 2: Editor Review

#221 Update people/README.md
  operations/workplace/people/README.md
Labels: 3: Reviews Complete

#219 Update new-staff-performance-review.md
  operations/workplace/people/performance-reviews-50/new-staff-performance-review.md
Labels: 3: Reviews Complete

#218 Create offboarding
  operations/workplace/people/offboarding
Labels: 3: Reviews Complete

#213 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 3: Reviews Complete

#223 Create mobile-feature-guidelines.md
  SUMMARY.md
  operations/research-and-development/product/development-process/mobile-feature-guidelines.md
Labels: 2: Editor Review

#216 Add a video on how to create a new page in GitHub
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#220 Corrections to MLT overview
  operations/operations/mlt-cadence/README.md
Labels: 2: Editor Review

#217 Update hr-cadences.md
  operations/workplace/people/hr-cadences.md
Labels: 1: SME Review

#225 Update company-cadence.md
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#228 Create workplace-program.md
  SUMMARY.md
  operations/workplace/people/working-at-mattermost/workplace-program.md
Labels: 3: Reviews Complete

#226 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 2: Editor Review

#233 Update time for video game
  operations/workplace/people/working-at-mattermost/workplace-program.md
Labels: 3: Reviews Complete

#234 Update how-to-use-productboard.md
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 3: Reviews Complete

#235 Update how-to-use-productboard.md
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 2: Editor Review

#236 Update feature-release.md
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 1: SME Review

#210 Update how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
Labels: 1: SME Review

#237 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#231 Update company-cadence.md
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#241 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#242 Update submitting-documentation-with-your-PR.md
  operations/operations/publishing/publishing-guidelines/submitting-documentation-with-your-PR.md
Labels: 3: Reviews Complete

#240 WIP: Update NPS Metrics Definition
  operations/business-operations/analytics/metrics-definitions.md
Labels: Work In Progress

#232 Update performance-reviews-50/README.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete

#227 Update README.md
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete

#245 Remove old link references to docs from Community Overview page
  contributors/contributors/community.md
Labels: 3: Reviews Complete

#239 Update README.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete
