Repository mattermost/mattermost-handbook, pull requests merged in 2020-08, with the labels that each got.

#383 Update README.md
  operations/finance/README.md
Labels: 1: SME Review

#382 Create deal-desk.md
  operations/finance/deal-desk.md
Labels: 1: SME Review

#385 Update README.md
  operations/finance/README.md
Labels: 1: SME Review

#387 Add presentation template to branding guidelines
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
Labels: 3: Reviews Complete

#386 Update README.md
  operations/finance/README.md
Labels: 1: SME Review

#388 Update SUMMARY.md
  SUMMARY.md
  operations/finance/README.md
Labels: 1: SME Review

#390 Update README.md
  contributors/join-us/staff-recruiting/README.md
Labels: 1: SME Review

#391 Update SUMMARY.md
  SUMMARY.md
Labels: 1: SME Review

#393 Update areas-of-responsibility.md
  operations/operations/areas-of-responsibility.md
Labels: 3: Reviews Complete

#394 Update staff-recruiting/README.md
  contributors/join-us/staff-recruiting/README.md
Labels: 3: Reviews Complete

#363 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#347 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#397 Update internal-transfers.md
  operations/workplace/people/working-at-mattermost/internal-transfers.md
Labels: 1: SME Review

#400 Update the Mobile Subscription Language
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 2: Editor Review

#403 Remove Belarus from regions we can hire from
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#404 Create Family & Friends Day.MD
  SUMMARY.md
  operations/workplace/people/working-at-mattermost/family-and-friends-day.md
Labels: 3: Reviews Complete

#398 Adding link to Rude Q&A
  operations/sales.md
Labels: 2: Editor Review

#401 Update staff-onboarding-guide/README.md
  contributors/onboarding/staff-onboarding-guide/README.md
Labels: 3: Reviews Complete

#402 Update internal-transfers.md
  operations/workplace/people/working-at-mattermost/internal-transfers.md
Labels: 1: SME Review

#405 Update targets.md
  operations/business-operations/analytics/targets.md
Labels: 1: SME Review
