Repository mattermost/mattermost-handbook, pull requests merged in 2020-09, with the labels that each got.

#411 Update deal-desk.md
  operations/finance/deal-desk.md
Labels: 1: SME Review

#406 Updates to CAO and e-sign process
  operations/operations/company-agreements.md
Labels: 1: SME Review

#413 Add content-marketing to table of contents
  SUMMARY.md
Labels: 3: Reviews Complete

#412 Create QA handbook pages and add initial info
  SUMMARY.md
  operations/research-and-development/quality/README.md
  operations/research-and-development/quality/qa-workflow/README.md
  operations/research-and-development/quality/testing-tips-and-tools.md
Labels: 1: SME Review

#423 Update how-to-compose-tweets.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-compose-tweets.md
Labels: 3: Reviews Complete

#409 Create github-sponsorship.md
  SUMMARY.md
  contributors/contributors/github-sponsorship.md
Labels: 1: SME Review, 2: Editor Review

#422 Update how-to-run-executive-dinners.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-run-executive-dinners.md
Labels: 3: Reviews Complete

#425 Update how-to-run-meetups.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-run-meetups.md
Labels: 3: Reviews Complete

#414 Added content marketing subpages
  SUMMARY.md
Labels: 3: Reviews Complete

#408 Update baby-bonding-parental-leave.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/baby-bonding-parental-leave.md
Labels: 1: SME Review

#416 Update how-to-create-screenshots-and-gifs.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
Labels: 3: Reviews Complete

#428 Update README.md
  operations/workplace/people/working-at-mattermost/README.md
Labels: 3: Reviews Complete

#421 Update how-to-run-meetups.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-run-meetups.md
Labels: 3: Reviews Complete

#426 Create security-policies.md
  operations/operations/company-policies/security-policies.md
Labels: 1: SME Review

#433 Create community-playbook.md
  SUMMARY.md
  contributors/contributors/community-playbook.md
Labels: 3: Reviews Complete

#435 Update SUMMARY.md
  SUMMARY.md
Labels: 1: SME Review

#432 Update feature-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#419 Update how-to-write-mattermost-recipes.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-write-mattermost-recipes.md
Labels: 3: Reviews Complete

#427 Create mattermost-editorial-calendar.md
  SUMMARY.md
  operations/messaging-and-math/content-marketing/mattermost-editorial-calendar.md
Labels: 2: Editor Review

#407 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#436 Update SUMMARY.md
  SUMMARY.md
Labels: 1: SME Review

#441 Update SUMMARY.md
  SUMMARY.md
Labels: 1: SME Review

#430 Update README.md
  operations/finance/risk-management/README.md
Labels: 1: SME Review

#447 Update how-to-do-a-post-escalation-post-mortem.md
  company/how-to-guides-for-staff/how-to-do-a-post-escalation-post-mortem.md
Labels: 2: Editor Review

#448 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#449 Create Hacktoberfest Event Organizer Guide for Mattermost
  .gitbook/assets/hacktoberfest-organizer-bot-message.png
  SUMMARY.md
  contributors/contributors/hacktoberfest-mattermost-organizer-guide.md
Labels: 3: Reviews Complete

#442 Adding Customer Risk Section
  operations/customer-success/README.md
Labels: 1: SME Review

#452 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#456 Update frequently-asked-questions.md
  contributors/onboarding/frequently-asked-questions.md
Labels: 3: Reviews Complete

#431 Update deal-desk.md
  operations/finance/deal-desk.md
Labels: 1: SME Review

#451 Create localization.md
  SUMMARY.md
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#455 Update internal-transfers.md
  operations/workplace/people/working-at-mattermost/internal-transfers.md
Labels: 2: Editor Review

#440 Update recruiting.md
  SUMMARY.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#466 Update community-response-policy.md
  operations/operations/company-policies/community-response-policy.md
Labels: 3: Reviews Complete

#462 Update roadmap-views.md
  operations/research-and-development/product/product-planning/roadmap-views.md
Labels: 3: Reviews Complete

#439 Update join-us/README.md
  contributors/join-us/README.md
Labels: 1: SME Review, 2: Editor Review

#470 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#469 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#460 Copy edits on performance review process
  operations/workplace/people/performance-reviews-50/README.md
Labels: 1: SME Review, 2: Editor Review

#463 Update release-plan.md
  operations/research-and-development/product/product-planning/release-plan.md
Labels: 3: Reviews Complete

#467 Update README.md
  operations/messaging-and-math/README.md
Labels: 3: Reviews Complete

#474 Update mobile-feature-guidelines.md
  operations/research-and-development/product/development-process/mobile-feature-guidelines.md
Labels: 3: Reviews Complete

#472 Update feature-requests.md
  operations/research-and-development/product/product-planning/feature-requests.md
Labels: 3: Reviews Complete

#468 Update internal-transfers.md
  operations/workplace/people/working-at-mattermost/internal-transfers.md
Labels: 2: Editor Review

#458 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#417 Update how-to-write-mattermost-case-studies.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-write-mattermost-case-studies.md
Labels: 3: Reviews Complete

#434 Create community-systems.md
  SUMMARY.md
  contributors/contributors/community-systems.md
Labels: 3: Reviews Complete

#475 Add response writing tips to community response policy
  operations/operations/company-policies/community-response-policy.md
Labels: 3: Reviews Complete

#481 Correction to instructions for creating redirects for in-product doc links
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#484 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete
