Repository mattermost/mattermost-handbook, pull requests merged in 2020-10, with the labels that each got.

#485 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#479 [MM-28060] Document Integrations team processes
  .gitbook/assets/security-generating-automated-security.png
  .gitbook/assets/security-notification.png
  .gitbook/assets/security-serialze-javascript.png
  .gitbook/assets/security-view-alerts.png
  operations/research-and-development/engineering/README.md
  operations/research-and-development/engineering/integrations.md
  operations/research-and-development/engineering/plugin-release-process.md
Labels: 3: Reviews Complete

#476 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#489 Update formal-review-process.md
  operations/workplace/people/performance-reviews-50/formal-review-process.md
Labels: 3: Reviews Complete

#493 Create accounts payable
  operations/finance/finance-operations/accounts-payable
Labels: 1: SME Review, 2: Editor Review

#490 Create Staff Member Expenses
  operations/finance/spending-company-money/staff-member-expenses.md
Labels: 1: SME Review, 2: Editor Review

#483 Budget.MD
  operations/finance/spending-company-money/budget.md
Labels: 1: SME Review

#471 Update launch-plan.md
  operations/research-and-development/product/product-planning/launch-plan.md
Labels: 3: Reviews Complete

#465 Update release-announcement.md
  operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
Labels: 3: Reviews Complete

#496 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#500 Rename staff-member-expenses.md to staff-member-expenses
  operations/finance/spending-company-money/staff-member-expenses
Labels: 3: Reviews Complete

#503 Update company-agreements.md
  operations/operations/company-agreements.md
Labels: 3: Reviews Complete

#487 Add notes about release issues to Plugin Release Process
  operations/research-and-development/engineering/plugin-release-process.md
Labels: 1: SME Review

#488 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#504 Update family-and-friends-day.md
  operations/workplace/people/working-at-mattermost/family-and-friends-day.md
Labels: 3: Reviews Complete

#509 Update performance-reviews/readme.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete

#508 Update and rename mattermost-communication.md
  operations/workplace/mattermost-remote-values.md
Labels: 3: Reviews Complete

#362 [wip] create terminology guide
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#511 Update spending-company-money.md
  operations/finance/spending-company-money.md
Labels: 2: Editor Review

#506 Update formal-review.md
  operations/workplace/people/performance-reviews-50/formal-review-process.md
Labels: 3: Reviews Complete

#505 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete

#513 Update community-response-policy.md
  operations/operations/company-policies/community-response-policy.md
Labels: 3: Reviews Complete

#516 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#519 Update release checklists
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#515 Fix broken link in TOC
  SUMMARY.md
Labels: 2: Editor Review

#520 Update content-marketing.md
  operations/messaging-and-math/content-marketing.md
Labels: 3: Reviews Complete

#502 Create internship-expense-policy.md
  operations/finance/spending-company-money/staff-member-expenses/internship-expense-policy.md
Labels: 1: SME Review

#499 Update budget.md
  operations/finance/spending-company-money/budget.md
Labels: 3: Reviews Complete

#525 Update Agency onboarding
  contributors/join-us/Agency onboarding
  contributors/join-us/agency-onboarding.md
Labels: 1: SME Review, 2: Editor Review

#526 Create contribution-guidelines.md
  SUMMARY.md
  contributors/contributors/contribution-guidelines.md
Labels: 1: SME Review

#524 Update SUMMARY.md
  .gitbook.yaml
  SUMMARY.md
  operations/finance/finance-operations/README.md
  operations/finance/finance-operations/accounts-payable.md
  operations/finance/finance-operations/accounts-receivable
  operations/finance/finance-operations/accounts-receivable.md
  operations/finance/finance-operations/treasury.md
  operations/finance/spending-company-money/staff-member-expenses/README.md
Labels: 3: Reviews Complete

#530 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete

#531 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete
