Repository mattermost/mattermost-handbook, pull requests merged in 2020-06, with the labels that each got.

#249 Update submitting-documentation-with-your-PR.md
  operations/operations/publishing/publishing-guidelines/submitting-documentation-with-your-PR.md
Labels: 3: Reviews Complete

#248 Update formal-review-process.md
  operations/workplace/people/performance-reviews-50/formal-review-process.md
Labels: 3: Reviews Complete

#253 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 2: Editor Review

#256 Add files via upload
  .gitbook/assets/productboard_portal_nav.png
Labels: 3: Reviews Complete

#250 Update how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
Labels: 3: Reviews Complete

#262 Moving metrics definitions from BizOps section to Company Measures
  SUMMARY.md
Labels: 3: Reviews Complete

#255 added instructions on finding the portal
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 3: Reviews Complete

#258 Updating BizOps Handbook Sections
  operations/business-operations/analytics/targets.md
  operations/business-operations/self-service.md
Labels: 1: SME Review

#263 Updates to post-mortems
  company/how-to-guides-for-staff/how-to-do-a-post-escalation-post-mortem.md
Labels: 3: Reviews Complete

#259 Added section on how to follow features
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 3: Reviews Complete

#266 Add offboarding doc to TOC, fix file extension
  SUMMARY.md
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete

#265 Update customer-support.md
  operations/business-operations/customer-support.md
Labels: 3: Reviews Complete

#271 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#254 Add community response policy
  SUMMARY.md
  contributors/onboarding/things-everyone-must-know.md
  operations/operations/company-policies/README.md
  operations/operations/company-policies/community-response-policy.md
  operations/operations/company-processes/README.md
Labels: 3: Reviews Complete

#270 File cleanup, fix broken images
  .gitbook/assets/Tooltipimage.png
  .gitbook/assets/actionimage.png
  .gitbook/assets/fieldimage.png
  .gitbook/assets/helptextimage.png
  .gitbook/assets/label_afterimage.png
  .gitbook/assets/labelimage.png
  .gitbook/assets/menuimage.png
  .gitbook/assets/titleimage.png
  .gitbook/assets/uitable2.png
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
  uitable1.png
  uitable2.png
Labels: 2: Editor Review

#268 Create internal-transfers
  operations/workplace/people/working-at-mattermost/internal-transfers.md
Labels: 2: Editor Review

#269 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#273 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete

#274 Update Analtyics Section
  .gitbook/assets/analytics_q2.png
  operations/business-operations/analytics/README.md
Labels: 1: SME Review

#276 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#275 Update brand-and-visual-design-guidelines.md
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
Labels: 3: Reviews Complete

#272 Update how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
Labels: 3: Reviews Complete

#282 Update README.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete

#283 Update formal-review-process.md
  operations/workplace/people/performance-reviews-50/formal-review-process.md
Labels: 3: Reviews Complete

#297 Update pregnancy-leave.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/pregnancy-leave.md
Labels: 3: Reviews Complete

#296 Update workplace-program.md
  operations/workplace/people/working-at-mattermost/workplace-program.md
Labels: 3: Reviews Complete

#293 Update business-travel-insurance.md
  operations/workplace/people/working-at-mattermost/travel/business-travel-insurance.md
Labels: 3: Reviews Complete

#289 Update approvals-and-iteration.md
  operations/workplace/approvals-and-iteration.md
Labels: 3: Reviews Complete

#288 Update groups.md
  operations/workplace/groups.md
Labels: 3: Reviews Complete

#286 Update informal-review-process.md
  operations/workplace/people/performance-reviews-50/informal-review-process.md
Labels: 3: Reviews Complete

#285 Update performance-review-timeline-winter-2019.md
  operations/workplace/people/performance-reviews-50/performance-review-timeline-winter-2019.md
Labels: 3: Reviews Complete

#284 Update midyear-performance-review-timeline-2020.md
  operations/workplace/people/performance-reviews-50/midyear-performance-review-timeline-2020.md
Labels: 3: Reviews Complete

#300 Update areas-of-responsibility.md
  operations/operations/areas-of-responsibility.md
Labels: 3: Reviews Complete

#298 Update README.md
  operations/workplace/people/working-at-mattermost/README.md
Labels: 2: Editor Review

#295 Update baby-bonding-parental-leave.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/baby-bonding-parental-leave.md
Labels: 3: Reviews Complete

#302 Update README.md
  operations/operations/publishing/README.md
Labels: 3: Reviews Complete

#299 Update web-properties.md
  operations/operations/publishing/web-properties.md
Labels: 3: Reviews Complete

#294 Update README.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/README.md
Labels: 3: Reviews Complete

#287 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete

#301 Update README.md
  operations/operations/mlt-cadence/README.md
Labels: 3: Reviews Complete

#304 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#305 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 3: Reviews Complete

#292 Update paid-time-off.md
  operations/workplace/people/working-at-mattermost/paid-time-off.md
Labels: 3: Reviews Complete

#290 Update README.md
  operations/workplace/people/README.md
Labels: 3: Reviews Complete

#306 Updating Customer Feedback section
  operations/customer-success/README.md
Labels: 1: SME Review

#307 Update README.md
  operations/customer-success/README.md
Labels: 1: SME Review

#308 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#251 Add educational content to style guide
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#312 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#313 Update README.md
  company/about-mattermost/README.md
Labels: 3: Reviews Complete

#291 Update hr-cadences.md
  operations/workplace/people/hr-cadences.md
Labels: 3: Reviews Complete

#314 Update midyear-performance-review-timeline-2020.md
  operations/workplace/people/performance-reviews-50/midyear-performance-review-timeline-2020.md
Labels: 3: Reviews Complete

#310 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 2: Editor Review

#311 Update README.md
  operations/customer-success/README.md
Labels: 2: Editor Review

#321 Update how-to-v2mom.md
  company/how-to-guides-for-staff/how-to-v2mom.md
Labels: 3: Reviews Complete

#267 User Interface Text Guidelines
  .gitbook/assets/Tooltipimage.png
  .gitbook/assets/actionimage.png
  .gitbook/assets/fieldimage.png
  .gitbook/assets/helptextimage.png
  .gitbook/assets/label_afterimage.png
  .gitbook/assets/labelimage.png
  .gitbook/assets/menuimage.png
  .gitbook/assets/titleimage.png
  .gitbook/assets/uitable1.png
  .gitbook/assets/uitable2.png
  Tooltipimage.png
  actionimage.png
  fieldimage.png
  helptextimage.png
  label_afterimage.png
  labelimage.png
  menuimage.png
  operations/research-and-development/product/user-interface-text-guidelines.md
  titleimage.png
  uitable1.png
  uitable2.png
Labels: 1: SME Review, 2: Editor Review

#322 Update submitting-documentation-with-your-PR.md
  operations/operations/publishing/publishing-guidelines/submitting-documentation-with-your-PR.md
Labels: 3: Reviews Complete

#324 Add new UI text guidelines page to TOC
  SUMMARY.md
Labels: 2: Editor Review

#318 Update mindsets.md
  company/about-mattermost/mindsets.md
Labels: 3: Reviews Complete

#327 Update README.md
  README.md
Labels: 1: SME Review
