Repository mattermost/mattermost-handbook, pull requests merged in 2020-11, with the labels that each got.

#536 Changing exec interviews to 55m, no 45m interviews
  contributors/join-us/exec-recruiting/README.md
Labels: 2: Editor Review

#535 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#534 Update README.md
  contributors/join-us/exec-recruiting/README.md
Labels: 3: Reviews Complete

#537 Update README.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete

#418 Update how-to-write-guest-blog-posts-for-mattermost-apps-and-services.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-write-guest-blog-posts-for-mattermost-apps-and-services.md
Labels: 1: SME Review

#538 Update BizOps Section
  operations/business-operations/README.md
Labels: 3: Reviews Complete

#533 Update Readme.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete

#541 Update README.md
  operations/business-operations/README.md
Labels: 3: Reviews Complete

#542 Update feature-release.md
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 2: Editor Review

#166 Update metrics-definitions.md
  operations/business-operations/analytics/metrics-definitions.md
Labels: 1: SME Review

#539 Update manager-onboarding-1.md
  contributors/onboarding/manager-onboarding-1.md
Labels: 2: Editor Review

#548 Update formal-review-process.md
  operations/workplace/people/performance-reviews-50/formal-review-process.md
Labels: 3: Reviews Complete

#549 Add "Desktop" under computer and tech guidelines
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete

#551 Update metric definitions for TES, TEDAS and TEMAS
  operations/business-operations/analytics/metrics-definitions.md
Labels: 1: SME Review, 2: Editor Review

#552 Update README.md
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete

#559 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#560 Updating MQL def link
  operations/business-operations/lead-management.md
Labels: 3: Reviews Complete

#561 Updated external links format
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete
