Repository mattermost/mattermost-handbook, pull requests merged in 2020-12, with the labels that each got.

#554 Update things-everyone-must-know.md
  contributors/onboarding/things-everyone-must-know.md
Labels: 3: Reviews Complete

#529 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete

#562 Update SUMMARY.md
  SUMMARY.md
Labels: 1: SME Review

#528 Update how-to-arrange-a-bounty-program.md
  company/how-to-guides-for-staff/how-to-purchase/how-to-arrange-a-bounty-program.md
Labels: 3: Reviews Complete

#564 Update things-everyone-must-know.md
  contributors/onboarding/things-everyone-must-know.md
Labels: 3: Reviews Complete

#568 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#558 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 1: SME Review

#570 Revert "Update offboarding.md"
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete

#571 Update dot-release.md
  operations/research-and-development/product/release-process/dot-release.md
  operations/research-and-development/product/release-process/security-release.md
Labels: 3: Reviews Complete

#569 Create helpdesk.md
  SUMMARY.md
  operations/IT/README.md
  operations/IT/helpdesk.md
Labels: 3: Reviews Complete

#565 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete

#576 Update mindsets.md
  company/about-mattermost/mindsets.md
Labels: 3: Reviews Complete

#574 Added Accrualify section
  .gitbook/assets/How to set up your Accrualify account 1.PNG
  .gitbook/assets/How to set up your Accrualify account 2.PNG
  .gitbook/assets/How-to-navigate-Accrualify-1.PNG
  .gitbook/assets/How-to-navigate-Accrualify-10.PNG
  .gitbook/assets/How-to-navigate-Accrualify-2.PNG
  .gitbook/assets/How-to-navigate-Accrualify-3.PNG
  .gitbook/assets/How-to-navigate-Accrualify-4.PNG
  .gitbook/assets/How-to-navigate-Accrualify-5.PNG
  .gitbook/assets/How-to-navigate-Accrualify-6.PNG
  .gitbook/assets/How-to-navigate-Accrualify-7.PNG
  .gitbook/assets/How-to-navigate-Accrualify-8.PNG
  .gitbook/assets/How-to-navigate-Accrualify-9.PNG
  .gitbook/assets/How-to-review-a-vendor-invoice-1.PNG
  .gitbook/assets/How-to-review-a-vendor-invoice-2.PNG
  .gitbook/assets/How-to-review-a-vendor-invoice-3.PNG
  .gitbook/assets/How-to-review-a-vendor-invoice-4.PNG
  .gitbook/assets/How-to-review-a-vendor-invoice-5.PNG
  .gitbook/assets/How-to-set-up-your-Accrualify-account-1.PNG
  .gitbook/assets/How-to-set-up-your-Accrualify-account-2.PNG
  SUMMARY.md
  operations/finance/spending-company-money/how-to-use-accrualify/README.md
  operations/finance/spending-company-money/how-to-use-accrualify/frequently-asked-questions.md
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-navigate-accrualify.md
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-review-a-vendor-invoice.md
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-set-up-your-account.md
Labels: 2: Editor Review

#573 Create Hardware Buy Back Policy.md
  operations/IT/hardware-buy-back-policy.md
Labels: 3: Reviews Complete

#572 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#578 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete
