Repository mattermost/mattermost-handbook, pull requests merged in 2020-07, with the labels that each got.

#326 Update README.md
  operations/workplace/people/README.md
Labels: 1: SME Review

#329 Added vision and customer segmentation section
  operations/customer-success/README.md
Labels: 3: Reviews Complete

#334 change for grammar
  company/how-to-guides-for-staff/how-to-purchase/how-to-on-board-as-a-vendor/README.md
Labels: 3: Reviews Complete

#336 Update documentation-style-guide.md
  operations/operations/publishing/publishing-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#342 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 3: Reviews Complete

#339 Create Recruiting Cadences
  contributors/join-us/staff-recruiting/recruiting-cadences.md
Labels: 2: Editor Review

#338 Create People Policies
  contributors/mattercon/people-policies.md
Labels: 2: Editor Review

#333 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 2: Editor Review

#309 Update feature-requests.md
  operations/research-and-development/product/product-planning/feature-requests.md
Labels: 3: Reviews Complete

#315 Update how-to-setup-a-1-1-channel.md
  company/how-to-guides-for-staff/how-to-setup-a-1-1-channel.md
Labels: 3: Reviews Complete

#337 Update staff-recruiting/README.md
  contributors/join-us/staff-recruiting/README.md
  contributors/join-us/staff-recruiting/recruiting-cadences.md
Labels: 2: Editor Review

#328 Update how-to-arrange-a-bounty-program.md
  company/how-to-guides-for-staff/how-to-purchase/how-to-arrange-a-bounty-program.md
Labels: 1: SME Review

#341 Update engineer-onboarding.md
  contributors/onboarding/staff-onboarding-guide/engineer-onboarding.md
Labels: 3: Reviews Complete

#319 Update list-of-terms.md
  company/about-mattermost/list-of-terms.md
Labels: 3: Reviews Complete

#317 Update business-model.md
  company/about-mattermost/business-model.md
Labels: 1: SME Review

#325 Adding link to customer reference report
  operations/messaging-and-math/README.md
Labels: 3: Reviews Complete

#332 Updated Procuring a Vendor
  company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
Labels: 3: Reviews Complete

#320 Update brand-and-visual-design-guidelines.md
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
Labels: 3: Reviews Complete

#331 Update Equipment section
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 1: SME Review

#355 Divvy credit card section
  company/how-to-guides-for-staff/how-to-purchase/request-a-divvy-virtual-credit-card.md
Labels: 1: SME Review, 2: Editor Review

#354 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#343 Update feature-requests.md
  operations/research-and-development/product/product-planning/feature-requests.md
Labels: 3: Reviews Complete

#348 Update README.md
  operations/operations/mlt-cadence/README.md
Labels: 2: Editor Review

#351 Update people/README.md
  operations/workplace/people/README.md
Labels: 1: SME Review

#364 Fix broken link for downloading EPS package
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
Labels: 3: Reviews Complete

#361 Update metrics-definitions.md
  operations/business-operations/analytics/metrics-definitions.md
Labels: 1: SME Review

#344 Update how-to-use-productboard.md
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 1: SME Review

#346 Update integrations-directory.md
  operations/research-and-development/product/how-to-guides-for-product/integrations-directory.md
Labels: 1: SME Review

#365 Create join-us/canddiates.md
  contributors/join-us/candidates.md
Labels: 3: Reviews Complete

#350 Create HR Systems
  operations/workplace/people/hr-systems.md
Labels: 3: Reviews Complete

#340 Update staff-recruiting/README.md
  contributors/join-us/staff-recruiting/README.md
Labels: 3: Reviews Complete

#330 Update README.md
  contributors/onboarding/staff-onboarding-guide/README.md
Labels: 3: Reviews Complete

#369 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#368 Update README.md
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 1: SME Review

#371 Update web-properties.md
  operations/operations/publishing/web-properties.md
Labels: 3: Reviews Complete

#377 Fix broken "Mattermost Community" link
  company/about-mattermost/README.md
Labels: 3: Reviews Complete

#372 Laptop Section and Other Computer Tech Section
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete

#376 Fix Link
  company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
Labels: 1: SME Review

#335 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#378 Update SUMMARY.md: New navigation proposal (workplace)
  SUMMARY.md
Labels: 3: Reviews Complete

#375 Create mattermost-communication.md
  operations/workplace/mattermost-communication.md
Labels: 3: Reviews Complete

#379 Update feature-release.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
  operations/research-and-development/product/release-process/bug-fix-release.md
  operations/research-and-development/product/release-process/dot-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#380 Update how-to-procure-a-vendor-contract.md
  company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
Labels: 3: Reviews Complete

#352 Create release-announcement.md
  SUMMARY.md
  operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
Labels: 3: Reviews Complete

#345 Update how-to-use-productboard.md
  operations/research-and-development/product/product-planning/how-to-use-productboard.md
Labels: 3: Reviews Complete
