Repository mattermost/mattermost-handbook, pull requests merged in 2020-03, with the labels that each got.

#53 Update company-cadence.md
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#51 Update issue-solution.md
  operations/operations/issue-solution.md
Labels: 1: PM Review

#63 Update quality-control-process.md
  operations/operations/publishing/quality-control-process.md
Labels: 3: Reviews Complete

#62 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 3: Reviews Complete

#68 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#64 Replacing "work anywhere" language
  operations/workplace/people/working-at-mattermost/README.md
Labels: 3: Reviews Complete

#54 Approved reviewers and permissions to handbook process
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#71 Update README.md
  contributors/join-us/README.md
Labels: 3: Reviews Complete

#72 Update page description
  operations/workplace/people/working-at-mattermost/README.md
Labels: 3: Reviews Complete

#73 Update ISP handbook per Version 2 ISP
  operations/operations/issue-solution.md
Labels: 3: Reviews Complete

#75 Update README.md
  operations/operations/publishing/README.md
Labels: 3: Reviews Complete

#76 Update README.md
  operations/customer-success/README.md
Labels: 3: Reviews Complete

#60 Update company-agreements.md
  operations/operations/company-agreements.md
Labels: 3: Reviews Complete

#69 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#81 Update metrics-definitions.md
  operations/business-operations/analytics/metrics-definitions.md
Labels: 3: Reviews Complete

#82 Update README.md
  operations/operations/publishing/publishing-guidelines/README.md
Labels: 3: Reviews Complete

#83 Update metrics-definitions.md
  operations/business-operations/analytics/metrics-definitions.md
Labels: 1: SME Review

#85 Update company-cadence.md
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#87 Update list-of-terms.md
  company/about-mattermost/list-of-terms.md
Labels: 3: Reviews Complete

#88 Update list-of-terms.md
  company/about-mattermost/list-of-terms.md
Labels: 3: Reviews Complete

#92 Create HR Cadences
  SUMMARY.md
  operations/workplace/people/hr-cadences.md
Labels: 3: Reviews Complete

#97 Minor updates to "MLT Cadence" section
  operations/operations/company-metrics/company-v2mom-metrics.md
  operations/operations/mlt-cadence/README.md
Labels: 2: Editor Review

#77 Update Recruiting page.md
  contributors/join-us/recruiting.md
Labels: 1: SME Review

#101 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#102 Update and rename Readme.md to onboarding.md
  contributors/onboarding/README.md
  contributors/onboarding/onboarding.md
Labels: 3: Reviews Complete

#99 Adding links to channels in docs
  operations/workplace/README.md
Labels: 3: Reviews Complete

#95 Update mattermost-templated-agreements.md
  operations/finance/risk-management/mattermost-templated-agreements.md
Labels: 1: SME Review

#115 Updating company-cadence.md
  operations/operations/company-cadence.md
Labels: 2: Editor Review
