Repository mattermost/mattermost-handbook, pull requests merged in 2021-12, with the labels that each got.

#887 Update README.md
  operations/research-and-development/product/product-management-team-handbook/README.md
Labels: 3: Reviews Complete

#907 Corporate Credit Card Policy
  operations/finance/staff-member-expenses/corporate-credit-card-policy.md
Labels: 3: Reviews Complete

#909 Updated Translation Maintenance List
  contributors/join-us/localization.md
Labels: 1: SME Review, 2: Editor Review

#914 Update uploading-contracts.md
  operations/legal/contracts/uploading-contracts.md
Labels: 3: Reviews Complete

#913 Update third-party-review.md
  operations/legal/contracts/third-party-review.md
Labels: 3: Reviews Complete

#912 Update requesting-sales-contracts.md
  operations/legal/contracts/requesting-sales-contracts.md
Labels: 3: Reviews Complete

#910 Add page on MLX Growth Meeting
  operations/mlx-meetings.md
  operations/operations/previous-fiscal-year-information.md
Labels: 3: Reviews Complete

#917 Update company-cadence.md
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#916 Proposal to include certain metrics and analysis
  operations/operations/company-processes/publishing/publishing-guidelines/confidentiality-guidelines.md
Labels: 2: Editor Review, help wanted

#836 Update user-interface-text-guidelines.md
  operations/research-and-development/product/development-process/user-interface-text-guidelines.md
Labels: 3: Reviews Complete

#882 Update documentation-style-guide.md
  operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#920 Adding links to Mattermost 6 and key materials
  README.md
Labels: 3: Reviews Complete

#919 Create software-systems.md
  SUMMARY.md
  operations/workplace/it/software-systems.md
Labels: 1: SME Review

#922 Update hardware-buy-back-policy.md
  operations/workplace/it/hardware-buy-back-policy.md
Labels: 3: Reviews Complete

#925 Create desktop-release.md
  SUMMARY.md
  operations/research-and-development/product/release-process/desktop-release.md
Labels: 3: Reviews Complete

#928 Separate some Growth initiatives to Cloud & Self-Service specifically
  operations/research-and-development/product/product-management-team-handbook/product-ownership-areas.md
Labels: 3: Reviews Complete

#929 Add product analyst engineer + new hire to core committers list
  contributors/contributors/core-committers.md
Labels: 3: Reviews Complete
