Repository mattermost/mattermost-handbook, pull requests merged in 2021-02, with the labels that each got.

#604 Update feature-release.md
  operations/research-and-development/product/release-process/dot-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#607 Update sales.md
  operations/sales.md
Labels: 3: Reviews Complete

#609 Update content
  operations/finance/README.md
Labels: 3: Reviews Complete

#605 Clarify release processes
  .gitbook/assets/release-dates.png
  operations/research-and-development/product/development-process/mobile-feature-guidelines.md
  operations/research-and-development/product/release-process/release-overview.md
Labels: 3: Reviews Complete

#557 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 1: SME Review

#482 Update manager-onboarding-1.md
  contributors/onboarding/manager-onboarding-1.md
Labels: 1: SME Review

#424 Update README.md
  operations/messaging-and-math/README.md
Labels: 1: SME Review

#625 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 2: Editor Review

#443 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 1: SME Review, 2: Editor Review

#626 Update README.md
  operations/business-operations/README.md
Labels: 3: Reviews Complete

#624 New page
  operations/finance/spending-company-money/how-to-use-accrualify/Vendor Portal guide.md
Labels: 2: Editor Review

#623 Added new page
  operations/finance/purchasing.md
Labels: 2: Editor Review

#631 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/product-technical-writing-team-handbook.md
Labels: 3: Reviews Complete

#627 Update data-engineering.md
  operations/business-operations/data-engineering.md
Labels: 1: SME Review

#636 Clean up release checklists
  operations/research-and-development/product/release-process/cloud-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#637 Update localization.md
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#641 Adding SVG files for logos to use in handbook
  .gitbook/assets/branding/icon.svg
  .gitbook/assets/branding/iconBlue.svg
  .gitbook/assets/branding/iconWhite.svg
  .gitbook/assets/branding/logoHorizontal.svg
  .gitbook/assets/branding/logoHorizontalBlue.svg
  .gitbook/assets/branding/logoHorizontalWhite.svg
  .gitbook/assets/branding/logoVertical.svg
  .gitbook/assets/branding/logoVerticalBlue.svg
  .gitbook/assets/branding/logoVerticalWhite.svg
Labels: 3: Reviews Complete
