Repository mattermost/mattermost-handbook, pull requests merged in 2021-06, with the labels that each got.

#727 Add Najla Dadmand to core committers
  contributors/contributors/core-committers.md
Labels: 2: Editor Review

#726 Update README.md
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete

#731 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete

#732 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete

#734 Update .gitbook.yaml
  .gitbook.yaml
Labels: 2: Editor Review

#735 Update .gitbook.yaml
  .gitbook.yaml
Labels: 3: Reviews Complete

#730 Make reporting email a link
  contributors/contributors/contribution-guidelines.md
Labels: 3: Reviews Complete

#739 Update pregnancy-leave.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/pregnancy-leave.md
Labels: 3: Reviews Complete

#740 Update baby-bonding-parental-leave.md
  operations/workplace/people/working-at-mattermost/leaves-of-absence/baby-bonding-parental-leave.md
Labels: 3: Reviews Complete

#743 Remove translations reviewer
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#742 Updating QA items on self-managed and mobile release checklists
  operations/research-and-development/product/release-process/feature-release.md
  operations/research-and-development/product/release-process/mobile-release.md
Labels: 3: Reviews Complete

#745 Update README.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 1: SME Review, 2: Editor Review

#744 New product team hangouts
  SUMMARY.md
  operations/research-and-development/product/README.md
  operations/research-and-development/product/product-team-hangouts.md
Labels: 3: Reviews Complete

#737 Added reporting guidelines to Code of Conduct
  contributors/contributors/contribution-guidelines.md
Labels: 3: Reviews Complete

#750 Update core-committers.md
  contributors/contributors/core-committers.md
Labels: 3: Reviews Complete

#756 Added AORs
  operations/finance/README.md
Labels: 2: Editor Review

#757 Added vacation delegate
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-set-up-your-account.md
Labels: 2: Editor Review

#729 Update README.md
  contributors/contributors/core-committers.md
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#760 Update core-committers.md
  contributors/contributors/core-committers.md
Labels: 3: Reviews Complete

#755 Update contributing-content.md
  operations/messaging-and-math/content-marketing/contributing-content.md
Labels: 3: Reviews Complete

#759 Update M&M README.md
  operations/messaging-and-math/README.md
Labels: 3: Reviews Complete

#761 Create archive directory for deprecation
  company/archive/README.md
  company/archive/company-v2mom-metrics.md
  company/archive/how-to-v2mom.md
  company/archive/mlt-cadence-vpmom.md
  company/archive/performance-review-timeline-winter-2019.md
  company/archive/previous-fiscal-year-information.md
Labels: 1: SME Review, 3: Reviews Complete

#720 Update areas-of-responsibility.md
  operations/operations/areas-of-responsibility.md
Labels: 1: SME Review

#453 Create partner-programs.md
  SUMMARY.md
  operations/finance/partner-programs.md
Labels: 3: Reviews Complete

#741 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 2: Editor Review

#711 Update recruiting-cadences.md
  contributors/join-us/staff-recruiting/recruiting-cadences.md
Labels: 1: SME Review

#762 Update family-and-friends-day.md
  operations/workplace/people/working-at-mattermost/family-and-friends-day.md
Labels: 1: SME Review, 2: Editor Review

#728 Multi-product release docs
  operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
  operations/research-and-development/product/release-process/feature-release.md
  operations/research-and-development/product/release-process/focalboard-release.md
  operations/research-and-development/product/release-process/incident-collaboration-release.md
  operations/research-and-development/product/release-process/release-overview.md
  operations/research-and-development/product/release-process/release-tips.md
Labels: 1: SME Review, 2: Editor Review

#766 Add latest and edge terminology
  company/about-mattermost/list-of-terms.md
Labels: 3: Reviews Complete

#765 Update README.md
  operations/operations/mlt-cadence/README.md
Labels: 3: Reviews Complete

#763 Update paid-time-off
  operations/workplace/people/working-at-mattermost/paid-time-off.md
Labels: 3: Reviews Complete

#722 Update product-management-team-handbook.md
  SUMMARY.md
  operations/research-and-development/product/pm-onboarding.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#768 Update incident-collaboration-release.md
  operations/research-and-development/product/release-process/incident-collaboration-release.md
Labels: 1: SME Review

#767 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 2: Editor Review

#769 Update mattercon2021.md
  contributors/mattercon/mattercon2021.md
Labels: 1: SME Review

#771 Update team name in handbook
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#773 Update mattercon2021.md
  contributors/mattercon/mattercon2021.md
Labels: 3: Reviews Complete

#772 Updating AOR link
  operations/operations/areas-of-responsibility.md
Labels: 3: Reviews Complete

#774 Create documentation-contributions.md
  SUMMARY.md
  contributors/contributors/documentation-contributions.md
  contributors/contributors/ways-to-contribute.md
Labels: 3: Reviews Complete

#753 Adding guidelines
  operations/messaging-and-math/developer-relations.md
Labels: 3: Reviews Complete
