Repository mattermost/mattermost-handbook, pull requests merged in 2021-05, with the labels that each got.

#691 Update feature-release.md
  operations/research-and-development/product/release-process/feature-release.md
Labels: 3: Reviews Complete

#693 Update product-ownership-areas.md
  operations/research-and-development/product/product-ownership-areas.md
Labels: 3: Reviews Complete

#692 Adding Hungarian
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#694 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#688 Update Equipment Guideline Wordings to Engineers
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 1: SME Review

#687 Remove & Reorganize Old BizOps Sections
  .gitbook/assets/bizops_image.png
  .gitbook/assets/ops_ownership.png
  SUMMARY.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
  contributors/onboarding/staff-onboarding-guide/README.md
  operations/business-operations/README.md
  operations/business-operations/analytics/looker/README.md
  operations/business-operations/analytics/targets.md
  operations/business-operations/marketing-operations.md
  operations/business-operations/sales-operations&order-admin.md
  operations/business-operations/salesforce-administration.md
  operations/business-operations/vpmom.md
  operations/customer-success/customer-support.md
  operations/finance/deal-desk.md
  operations/messaging-and-math/demand-generation-reporting.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-add-tech-alliance.md
  operations/messaging-and-math/lead-management.md
  operations/research-and-development/engineering/data-engineering.md
  operations/research-and-development/engineering/self-service.md
  operations/research-and-development/product/analytics/README.md
  operations/research-and-development/product/analytics/looker/README.md
  operations/research-and-development/product/analytics/looker/dashboards.md
  operations/research-and-development/product/analytics/looker/explores.md
  operations/research-and-development/product/analytics/metrics-definitions.md
  operations/research-and-development/product/analytics/telemetry.md
  operations/sales.md
Labels: 3: Reviews Complete

#699 Update community-response-policy.md
  operations/operations/company-policies/community-response-policy.md
Labels: 3: Reviews Complete

#698 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 1: SME Review

#701 Update data-engineering.md
  operations/research-and-development/engineering/data-engineering.md
Labels: 1: SME Review

#703 Update family-and-friends-day.md
  operations/workplace/people/working-at-mattermost/family-and-friends-day.md
Labels: 3: Reviews Complete

#690 Update product-technical-writing-team-handbook.md
  operations/research-and-development/product/technical-writing/docathon-processes.md
  operations/research-and-development/product/technical-writing/product-technical-writing-team-handbook.md
  operations/research-and-development/product/technical-writing/product-technical-writing-workflows.md
Labels: 3: Reviews Complete

#702 Update how-to-create-screenshots-and-gifs.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-screenshots-and-gifs.md
Labels: 3: Reviews Complete

#700 Move DevRel from Marketing to R&D>Product
  .gitbook.yaml
  SUMMARY.md
Labels: 3: Reviews Complete

#696 Add R&D teams to R&D section
  SUMMARY.md
  contributors/contributors/core-committers.md
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#706 Update README.md
  operations/research-and-development/README.md
Labels: 1: SME Review

#697 MatterCon2021update
  .gitbook/assets/mattercon2021teamroom.png
  SUMMARY.md
  contributors/mattercon/README.md
  contributors/mattercon/mattercon2020.md
  contributors/mattercon/mattercon2021.md
Labels: 3: Reviews Complete

#681 Update integrations.md
  operations/research-and-development/engineering/integrations.md
Labels: 1: SME Review

#707 Update release-planning-process.md
  operations/research-and-development/product/product-planning/release-planning-process.md
Labels: 3: Reviews Complete

#708 Update R&D README.md
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#710 Update mattercon2021.md
  contributors/mattercon/mattercon2021.md
Labels: 3: Reviews Complete

#715 Update docs based on new async triage process
  operations/research-and-development/product/development-process/bug-severity-guidelines.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 2: Editor Review

#713 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#718 Update release-planning-process.md
  operations/research-and-development/product/product-planning/release-planning-process.md
Labels: 2: Editor Review

#717 Update product-ownership-areas.md
  operations/research-and-development/product/product-ownership-areas.md
Labels: 3: Reviews Complete

#719 Update README.md
  operations/operations/publishing/README.md
Labels: 3: Reviews Complete

#721 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#725 Update mattercon2021.md
  contributors/mattercon/mattercon2021.md
Labels: 2: Editor Review

#724 Update to Software section
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete
