Repository mattermost/mattermost-handbook, pull requests merged in 2021-08, with the labels that each got.

#803 Add a link to how to update the handbook in 'contact us' page
  contact-us.md
Labels: 3: Reviews Complete

#804 Update README.md
  operations/finance/README.md
Labels: 1: SME Review

#806 Update how-to-update-handbook.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#705 Add community engagement guidelines, reorganize Contributors section
  SUMMARY.md
  contributors/contributors/guidelines.md
  contributors/contributors/social-engagement-guidelines.md
Labels: 1: SME Review

#807 Update QA section README.md
  operations/research-and-development/quality/README.md
Labels: Docathon 2021

#808 Create ice-breakers.md
  SUMMARY.md
  contributors/join-us/ice-breakers.md
Labels: 2: Editor Review, Docathon 2021

#809 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 2: Editor Review, Docathon 2021

#800 Create Handbook section
  SUMMARY.md
  operations/operations/handbook/README.md
  operations/operations/handbook/handbook-onboarding.md
Labels: 2: Editor Review

#811 Update README.md
  contributors/join-us/staff-recruiting/README.md
Labels: 3: Reviews Complete

#813 Adding link to AA process
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#819 add legal page to handbook
  SUMMARY.md
  operations/legal/legal.md
Labels: 2: Editor Review

#820 Update link to slide template
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
Labels: 2: Editor Review

#818 Create new page for how to help improve Mattermost
  contributors/contributors/ways-to-contribute.md
Labels: 3: Reviews Complete

#821 First draft - Contributor Kindness
  contributors/contributors/contributor-kindness.md
Labels: 2: Editor Review

#826 Added Expectation & "Can you respond to this" section to handbook
  contributors/contributors/guidelines/social-engagement-guidelines.md
Labels: 3: Reviews Complete

#825 Update legal.md
  operations/legal.md
Labels: 3: Reviews Complete

#823 Adding ab testing methodology to new growth section in handbook.
  .DS_Store
  .gitbook/.DS_Store
  .gitbook/assets/z-score-table.png
  company/.DS_Store
  contributors/.DS_Store
  operations/.DS_Store
  operations/research-and-development/.DS_Store
  operations/research-and-development/product/.DS_Store
  operations/research-and-development/product/growth/ab-testing.md
Labels: 2: Editor Review

#828 Add A/B testing methodology to the TOC
  SUMMARY.md
  operations/research-and-development/product/growth/README.md
Labels: 3: Reviews Complete
