Repository mattermost/mattermost-handbook, pull requests merged in 2021-09, with the labels that each got.

#835 Update Finance team README.md
  operations/finance/README.md
Labels: 1: SME Review

#838 Add Product Manger intern Stephen to handbook
  contributors/contributors/core-committers.md
Labels: 2: Editor Review

#839 Update internship-expense-policy.md
  operations/finance/staff-member-expenses/internship-expense-policy.md
Labels: 3: Reviews Complete

#837 Update documentation-style-guide.md
  operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/documentation-style-guide.md
Labels: 3: Reviews Complete

#841 Update README.md
  operations/research-and-development/README.md
Labels: 2: Editor Review

#844 Fix typos in SET docs
  operations/research-and-development/engineering/team/README.md
Labels: 3: Reviews Complete

#843 Update README.md
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#847 Add Community Content Program
  SUMMARY.md
  contributors/contributors/ways-to-contribute/community-content-program.md
Labels: 3: Reviews Complete

#851 Add Hacktoberfest page to SUMMARY
  SUMMARY.md
Labels: 2: Editor Review

#850 Making it clear AA interviews are required
  operations/workplace/people/internal-transfers.md
Labels: 3: Reviews Complete

#848 Added section about weekly escalated accounts meeting for SET
  operations/research-and-development/engineering/team/README.md
Labels: 3: Reviews Complete

#854 Update how-to-spend-company-money.md
  operations/finance/staff-member-expenses/how-to-spend-company-money.md
Labels: 3: Reviews Complete

#853 Mattermost Handbook > Localization Updates
  contributors/join-us/localization.md
Labels: 3: Reviews Complete

#852 Update Mattermost Consulting Agreement Page
  operations/finance/risk-management/mattermost-templated-agreements.md
Labels: 3: Reviews Complete

#846 Update staff-recruiting.md
  contributors/join-us/staff-recruiting.md
Labels: 3: Reviews Complete

#845 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete
