Repository mattermost/mattermost-handbook, pull requests merged in 2021-04, with the labels that each got.

#630 Update product-management-team-handbook.md
  operations/research-and-development/product/product-management-team-handbook.md
Labels: 3: Reviews Complete

#659 Update business-model.md
  company/about-mattermost/business-model.md
Labels: 3: Reviews Complete

#527 Update contribution-guidelines.md
  contributors/contributors/contribution-guidelines.md
Labels: 1: SME Review

#521 Create video-content.md
  SUMMARY.md
  operations/messaging-and-math/content-marketing/video-content.md
Labels: 2: Editor Review

#667 Update README.md
  operations/operations/mlt-cadence/README.md
Labels: 3: Reviews Complete

#672 Replacing "High Standards" with "Earn Trust"
  operations/workplace/approvals-and-iteration.md
Labels: 3: Reviews Complete

#665 Update README.md
  company/about-mattermost/README.md
Labels: 3: Reviews Complete

#670 Per COM, consolidating core values
  contributors/onboarding/staff-onboarding-guide/README.md
Labels: 3: Reviews Complete

#671 Per COM, consolidating core values
  README.md
Labels: 3: Reviews Complete

#674 Update approvals-and-iteration.md
  operations/workplace/approvals-and-iteration.md
Labels: 3: Reviews Complete

#647 Update release-announcement.md
  operations/research-and-development/product/how-to-guides-for-product/release-announcement.md
Labels: 3: Reviews Complete

#673 Update release-scorecard-definitions.md
  operations/research-and-development/product/release-process/release-scorecard-definitions.md
Labels: 3: Reviews Complete

#678 Update integrations.md
  operations/research-and-development/engineering/integrations.md
Labels: 1: SME Review, 2: Editor Review

#677 Add a few steps to release checklist
  operations/research-and-development/product/release-process/cloud-release.md
  operations/research-and-development/product/release-process/feature-release.md
  operations/research-and-development/product/release-process/mobile-release.md
Labels: 3: Reviews Complete

#675 Update Staff-Recruiting/README.md
  contributors/join-us/staff-recruiting/README.md
Labels: 1: SME Review

#683 Matthewbirtch patch 1
  .gitbook/assets/brand-and-visual-design-guidelines-logo-horizontal-blue.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-horizontal-clear-space.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-horizontal-white.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-horizontal.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-intro.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-logomark-blue.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-logomark-white.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-logomark.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-vertical-blue.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-vertical-clear-space.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-vertical-white.png
  .gitbook/assets/brand-and-visual-design-guidelines-logo-vertical.png
  .gitbook/assets/brand-and-visual-design-guidelines-logos-clearspace.png
  .gitbook/assets/brand-and-visual-design-guidelines-logos-horizontal.png
  .gitbook/assets/brand-and-visual-design-guidelines-logos-logomarks.png
  .gitbook/assets/brand-and-visual-design-guidelines-logos-vertical.png
  .gitbook/assets/brand-and-visual-design-guidelines-presentation-sample-slides.png
  .gitbook/assets/branding/icon.png
  .gitbook/assets/branding/iconBlue.png
  .gitbook/assets/branding/iconWhite.png
  .gitbook/assets/branding/logoHorizontal.png
  .gitbook/assets/branding/logoHorizontalBlue.png
  .gitbook/assets/branding/logoHorizontalWhite.png
  .gitbook/assets/branding/logoVertical.png
  .gitbook/assets/branding/logoVerticalBlue.png
  .gitbook/assets/branding/logoVerticalWhite.png
  operations/operations/publishing/publishing-guidelines/brand-and-visual-design-guidelines.md
Labels: 3: Reviews Complete

#685 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#676 manager-onboarding-1.md
  contributors/onboarding/manager-onboarding-1.md
Labels: 3: Reviews Complete

#679 Updates to Finance
  operations/finance/README.md
Labels: 3: Reviews Complete

#682 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete
