Repository mattermost/mattermost-handbook, pull requests merged in 2021-11, with the labels that each got.

#880 Update README.md
  operations/workplace/people/working-at-mattermost/paid-time-off/README.md
Labels: 1: SME Review

#885 Create writer-levels.md
  SUMMARY.md
  operations/research-and-development/product/technical-writing-team-handbook/writer-levels.md
Labels: 3: Reviews Complete

#883 Update core committers - add new PMs
  contributors/contributors/core-committers.md
Labels: 1: SME Review

#884 Create pm-levels.md
  SUMMARY.md
  operations/research-and-development/product/product-management-team-handbook/pm-levels.md
Labels: 1: SME Review

#888 Add bug bash tips
  operations/research-and-development/product/release-process/release-tips.md
Labels: 3: Reviews Complete

#881 Update cloud fast-forward process doc section
  operations/research-and-development/product/release-process/release-overview.md
Labels: 1: SME Review

#890 Update README.md
  operations/workplace/people/performance-reviews-50/README.md
Labels: 3: Reviews Complete

#891 Update formal-review-process.md
  operations/workplace/people/performance-reviews-50/formal-review-process.md
Labels: 3: Reviews Complete

#892 Add Don Hogan to core committers list
  contributors/contributors/core-committers.md
Labels: 2: Editor Review

#805 Update offboarding.md
  operations/workplace/people/offboarding.md
Labels: 3: Reviews Complete

#900 Wording change to emotion, assumption, priority
  company/about-mattermost/mindsets.md
Labels: 3: Reviews Complete

#893 Create requesting-template-in-spotdraft.md
  operations/legal/contracts/requesting-template-in-spotdraft.md
Labels: 3: Reviews Complete

#901 Add guidelines for sensitive PRs
  SUMMARY.md
  operations/security/product-security/README.md
  operations/security/product-security/working-on-sensitive-prs.md
Labels: 3: Reviews Complete

#904 Update DevOps channel link to an active channel
  company/how-to-guides-for-staff/how-to-update-handbook.md
Labels: 3: Reviews Complete

#906 Update product-ownership-areas.md
  operations/research-and-development/product/product-management-team-handbook/product-ownership-areas.md
Labels: 3: Reviews Complete
