Repository mattermost/mattermost-handbook, pull requests merged in 2021-10, with the labels that each got.

#861 Updated link for Hacktoberfest2021 in resources
  contributors/events/hacktoberfest2021.md
Labels: hacktoberfest-accepted, Hacktoberfest

#858 Use the spreadsheet to track the R&D org as the single source of truth
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#855 Add terms and conditions
  contributors/contributors/ways-to-contribute/community-content-program.md
Labels: 1: SME Review, 2: Editor Review

#842 Update core-committers.md
  contributors/contributors/core-committers.md
Labels: 1: SME Review

#859 Add organization secton to R&D for describing overall structure layout
  SUMMARY.md
  operations/research-and-development/organization/README.md
  operations/research-and-development/organization/channels.md
Labels: 1: SME Review
