Repository mattermost/mattermost-handbook, pull requests merged in 2021-07, with the labels that each got.

#777 Update issue-solution.md
  operations/operations/issue-solution.md
Labels: 2: Editor Review

#776 Update README.md
  company/how-to-guides-for-staff/how-to-spend-company-money/README.md
Labels: 3: Reviews Complete

#778 Adjust security process to notify GitLab team in their Slack channel
  operations/research-and-development/product/release-process/security-release.md
Labels: 1: SME Review

#780 Adding Self-Serve Analytics Metric Definition Documentation to MM Handbook.
  operations/operations/company-metrics/metrics.md
Labels: 2: Editor Review

#779 Add Cloud Infrastructure Cost KPI definitions into the handbook
  SUMMARY.md
  operations/research-and-development/engineering/cloud-infrastructure-cost-kpis.md
Labels: 3: Reviews Complete

#781 Adding official reviewer for Bulgarian and English-Australian translations
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#784 Add CRT
  company/about-mattermost/list-of-terms.md
Labels: 3: Reviews Complete

#782 Update README.md
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#785 Creating an Event Code of Conduct
  operations/messaging-and-math/event-code-of-conduct.md
Labels: 2: Editor Review

#787 Update R&D team page with new team names and Ashish joining Apollo
  operations/research-and-development/README.md
Labels: 2: Editor Review

#786 Create docathon page for docathon 2021
  SUMMARY.md
  operations/research-and-development/product/technical-writing/community-documentation-process.md
  operations/research-and-development/product/technical-writing/docathon-2021.md
  operations/research-and-development/product/technical-writing/docathon-processes.md
Labels: 1: SME Review

#788 Update README.md
  operations/research-and-development/README.md
Labels: 3: Reviews Complete

#789 Update docathon-2021.md
  operations/research-and-development/product/technical-writing/docathon-2021.md
Labels: 3: Reviews Complete

#770 Update mattercon2021.md
  contributors/mattercon/mattercon2021.md
Labels: 3: Reviews Complete

#415 Update how-to-create-release-announcements.md
  operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-create-release-announcements.md
Labels: 2: Editor Review

#783 Moving IT section within Workplace
  .gitbook.yaml
  SUMMARY.md
Labels: 3: Reviews Complete

#754 Initial Commit for Security Section in Handbook
  SUMMARY.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
  operations/security/README.md
  operations/security/policies/README.md
  operations/security/privacy/README.md
  operations/security/privacy/data-deletion-requests.md
  operations/security/privacy/data-subject-access-requests.md
  operations/security/product-security/README.md
  operations/security/product-security/plugin-security-review.md
  operations/security/security-operations/README.md
  operations/security/security-operations/user-guides.md
Labels: 2: Editor Review, Department/Engineering

#664 Update internal-transfers.md
  SUMMARY.md
  operations/workplace/people/working-at-mattermost/internal-transfers.md
Labels: 1: SME Review

#791 Update people/README.md
  operations/workplace/people/README.md
Labels: 1: SME Review

#712 Update release-overview.md
  operations/research-and-development/product/release-process/release-overview.md
Labels: 3: Reviews Complete

#794 Update core-committers.md
  contributors/contributors/core-committers.md
Labels: 3: Reviews Complete

#796 Update docathon-2021.md
  operations/research-and-development/product/technical-writing/docathon-2021.md
Labels: 3: Reviews Complete

#802 First draft of new SET docs
  SUMMARY.md
  operations/research-and-development/engineering/sustained-engineering/on-call.md
  operations/research-and-development/engineering/sustained-engineering/team.md
Labels: 3: Reviews Complete

#792 Update README.md
  operations/workplace/people/README.md
Labels: 2: Editor Review

#799 Add documentation about the lifecycle of a Jira ticket
  SUMMARY.md
  operations/research-and-development/product/development-process/jira-ticket-lifecycle.md
Labels: 2: Editor Review, Docathon 2021

#797 Update recruiting.md
  contributors/join-us/recruiting.md
Labels: 3: Reviews Complete

#801 Update README.md
  README.md
Labels: 3: Reviews Complete
