Repository mattermost/mattermost-handbook, pull requests merged in 2021-01, with the labels that each got.

#577 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#583 Improving the DevRel Page
  operations/messaging-and-math/developer-relations.md
Labels: 2: Editor Review

#582 Update FAQs
  operations/finance/spending-company-money/how-to-use-accrualify/frequently-asked-questions.md
Labels: 3: Reviews Complete

#579 Added Review & Submit PO Images
  .gitbook/assets/How-to-review-a-PO-1.PNG
  .gitbook/assets/How-to-review-a-PO-2.PNG
  .gitbook/assets/How-to-review-a-PO-3.PNG
  .gitbook/assets/How-to-review-a-PO-4.PNG
  .gitbook/assets/How-to-review-a-PO-5.PNG
  .gitbook/assets/How-to-review-a-PO-6.PNG
  .gitbook/assets/How-to-review-a-PO-7.PNG
  .gitbook/assets/How-to-submit-a-PO-1.PNG
  .gitbook/assets/How-to-submit-a-PO-2.PNG
  .gitbook/assets/How-to-submit-a-PO-3.PNG
  .gitbook/assets/How-to-submit-a-PO-4.PNG
  .gitbook/assets/How-to-submit-a-PO-5.PNG
  .gitbook/assets/How-to-submit-a-PO-6.PNG
  .gitbook/assets/How-to-submit-a-PO-7.PNG
Labels: 3: Reviews Complete

#566 Update how-to-arrange-a-bounty-program.md
  company/how-to-guides-for-staff/how-to-purchase/how-to-arrange-a-bounty-program.md
Labels: 1: SME Review

#585 Updating reviewers and maintainers
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#587 Update how-to-procure-a-vendor-contract.md
  company/how-to-guides-for-staff/how-to-purchase/how-to-procure-a-vendor-contract.md
Labels: 3: Reviews Complete

#588 Update voice-tone-and-writing-style-guidelines.md
  operations/operations/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines.md
Labels: 1: SME Review

#580 Adding Submit PO
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-submit-a-po.md
Labels: 1: SME Review, 2: Editor Review

#581 Add Review PO
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-review-a-po.md
Labels: 1: SME Review, 2: Editor Review

#586 Update policy
  operations/IT/hardware-buy-back-policy.md
Labels: 2: Editor Review

#589 Adding new sections
  SUMMARY.md
Labels: 3: Reviews Complete

#594 Fixed links formatting in Localization.md
  contributors/contributors/localization.md
Labels: 3: Reviews Complete

#575 Update frequently-asked-questions.md
  contributors/onboarding/frequently-asked-questions.md
Labels: 3: Reviews Complete

#595 Updating Customer Risk
  operations/customer-success/README.md
Labels: 1: SME Review, 2: Editor Review

#596 Minor Changes to At Risk
  operations/customer-success/README.md
Labels: 1: SME Review

#598 Update paid-time-off.md
  operations/workplace/people/working-at-mattermost/paid-time-off.md
Labels: 2: Editor Review

#592 Update release-overview
  SUMMARY.md
  operations/research-and-development/product/release-process/cloud-release.md
  operations/research-and-development/product/release-process/feature-release.md
  operations/research-and-development/product/release-process/release-overview.md
  operations/research-and-development/product/release-process/release-tips.md
Labels: 3: Reviews Complete

#602 Update how-to-submit-a-po.md
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-submit-a-po.md
Labels: 1: SME Review

#601 Update how-to-review-a-po.md
  operations/finance/spending-company-money/how-to-use-accrualify/how-to-review-a-po.md
Labels: 3: Reviews Complete

#599 Update new-staff-performance-review.md
  operations/workplace/people/performance-reviews-50/new-staff-performance-review.md
Labels: 1: SME Review, 3: Reviews Complete

#600 Update README.md
  contributors/onboarding/README.md
Labels: 3: Reviews Complete

#603 Fix typo
  contributors/onboarding/staff-onboarding-guide/README.md
Labels: 2: Editor Review

#584 Update groups.md
  operations/workplace/groups.md
Labels: 1: SME Review
