Repository mattermost/mattermost-handbook, pull requests merged in 2022-02, with the labels that each got.

#964 Pc web was referring to ios instead of macos
  operations/research-and-development/product/development-process/software-requirements.md
Labels: 2: Editor Review

#960 Organization Structure Updates with AORs
  SUMMARY.md
  operations/research-and-development/organization/README.md
  operations/research-and-development/organization/boards.md
  operations/research-and-development/organization/calls.md
  operations/research-and-development/organization/channels.md
  operations/research-and-development/organization/cloud_platform.md
  operations/research-and-development/organization/data_engineering.md
  operations/research-and-development/organization/growth.md
  operations/research-and-development/organization/integrations_framework.md
  operations/research-and-development/organization/mobile.md
  operations/research-and-development/organization/playbooks.md
  operations/research-and-development/organization/product_security.md
  operations/research-and-development/organization/qa.md
  operations/research-and-development/organization/release_devops.md
  operations/research-and-development/organization/security_operations.md
  operations/research-and-development/organization/self-serve_subscriptions.md
  operations/research-and-development/organization/server.md
  operations/research-and-development/organization/sre.md
  operations/research-and-development/organization/suite_users.md
  operations/research-and-development/organization/tech_writing.md
  operations/research-and-development/organization/web_desktop.md
Labels: 1: SME Review

#974 Adding section for outside council
  operations/legal/legal.md
Labels: 3: Reviews Complete

#976 Fixing out-of-date references
  operations/finance/purchasing/how-to-procure-a-vendor-contract.md
Labels: 1: SME Review

#968 Update company-agreements.md
  operations/operations/company-processes/company-agreements.md
Labels: 1: SME Review
