Repository mattermost/mattermost-handbook, pull requests merged in 2022-12, with the labels that each got.

#1144 Fixed internal link syntax typo
  operations/research-and-development/product/technical-writing-team-handbook/documentation-style-guide.md
Labels: 2: Editor Review

#1141 Fixed typo
  operations/sales/partner-programs.md
Labels: 3: Reviews Complete

#1133 Fix the URL for recruiting new talent
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#1139 Updating page for How to setup okta 2FA in new mobile device
  company/how-to-guides-for-staff/how-to-change-mobile-device/README.md
Labels: 1: SME Review

#1149 How to omit error strings from L10n workflows
  contributors/join-us/localization.md
Labels: 2: Editor Review
