Repository mattermost/mattermost-handbook, pull requests merged in 2022-10, with the labels that each got.

#1097 Add developer conference policy to summary.md
  SUMMARY.md
Labels: 2: Editor Review

#1098 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#1099 Create hacktoberfest2022.md
  SUMMARY.md
  contributors/events/hacktoberfest2022.md
Labels: 3: Reviews Complete

#1090 Rename operations/operations/company-processes/publishing/publishing-…
  operations/operations/company-processes/publishing/publishing-guidelines/voice-tone-and-writing-style-guidelines/README.md
  operations/operations/operations/research-and-development/product/technical-writing-team-handbook/documentation-style-guide.md
Labels: 1: SME Review

#1095 address some typos in handbook
  company/about-mattermost/business-model.md
  company/about-mattermost/mindsets.md
  company/how-to-guides-for-staff/how-to-update-handbook.md
  operations/operations/company-processes/issue-solution.md
  operations/research-and-development/product/product-planning/product-philosophy-and-principles.md
Labels: hacktoberfest-accepted, Hacktoberfest

#1104 Update SUMMARY.md
  SUMMARY.md
Labels: 3: Reviews Complete

#1091 Create training.md
  operations/research-and-development/product/professional-development.md
Labels: 1: SME Review

#1088 Remove recommended readings link
  operations/finance/staff-member-expenses/how-to-spend-company-money.md
Labels: 3: Reviews Complete

#1101 Update dashboards.md
  operations/research-and-development/product/analytics/looker/dashboards.md
Labels: 2: Editor Review

#1113 UPDATE FINANCE TEAM INFO
  operations/finance/README.md
Labels: 3: Reviews Complete, hacktoberfest-accepted, Hacktoberfest

#1111 Updated dead link in "how-to-spend-company-money"
  operations/finance/staff-member-expenses/how-to-spend-company-money.md
Labels: 2: Editor Review, hacktoberfest-accepted, Hacktoberfest

#986 Add secure software development guide
  SUMMARY.md
  operations/research-and-development/product/development-process/secure-software-development.md
Labels: 1: SME Review, 2: Editor Review

#1114 UPDATE PAYROLL SECTION
  operations/finance/operations-playbook.md
Labels: 1: SME Review, hacktoberfest-accepted, Hacktoberfest

#1116 Update README.md
  contributors/mattercon/README.md
Labels: 3: Reviews Complete

#1084 Update total-rewards.md
  operations/workplace/people/total-rewards.md
Labels: 3: Reviews Complete
