Repository mattermost/mattermost-handbook, pull requests merged in 2022-01, with the labels that each got.

#934 Update mindsets.md
  company/about-mattermost/mindsets.md
Labels: 3: Reviews Complete

#931 Update corporate-credit-card-policy.md
  operations/finance/staff-member-expenses/corporate-credit-card-policy.md
Labels: 3: Reviews Complete

#933 Update operations-playbook.md
  .gitbook/assets/accounting-systems-flows-v2.png
  operations/finance/operations-playbook.md
Labels: 2: Editor Review, 3: Reviews Complete

#937 Update operations-playbook.md
  operations/finance/operations-playbook.md
Labels: 3: Reviews Complete

#936 Add product analyst levels
  SUMMARY.md
  operations/research-and-development/product/analytics/analyst-levels.md
Labels: 3: Reviews Complete

#938 Update product-ownership-areas.md
  operations/research-and-development/product/product-management-team-handbook/product-ownership-areas.md
Labels: 1: SME Review

#939 Update frequently-asked-questions.md
  operations/workplace/people/working-at-mattermost/onboarding/frequently-asked-questions.md
Labels: 3: Reviews Complete

#940 Compensation Approval Updates
  operations/workplace/approvals-and-iteration.md
Labels: 2: Editor Review

#941 Working on some iterative update here
  operations/operations/mlt-cadence/README.md
Labels: 3: Reviews Complete

#942 Moving G Doc into handbook for "Decision Making"
  operations/operations/company-processes/issue-solution.md
Labels: 3: Reviews Complete

#945 Updated the list of 2022 Holidays
  operations/workplace/people/working-at-mattermost/paid-time-off/README.md
Labels: 1: SME Review, 2: Editor Review

#889 Update Technical Writing team handbook
  operations/research-and-development/product/technical-writing-team-handbook/README.md
Labels: 3: Reviews Complete

#946 Update README.md
  operations/workplace/people/working-at-mattermost/paid-time-off/README.md
Labels: 3: Reviews Complete

#951 Update AA process
  contributors/join-us/staff-recruiting.md
Labels: 1: SME Review

#948 Update Boards release process
  SUMMARY.md
  operations/research-and-development/product/release-process/boards-release.md
Labels: 3: Reviews Complete

#886 Updated SET workflow
  operations/research-and-development/engineering/team/README.md
Labels: 1: SME Review

#950 Add Cloud churn support process to handbook
  SUMMARY.md
  operations/research-and-development/engineering/cloud-engineering/README.md
  operations/research-and-development/engineering/cloud-engineering/cloud-churn-process.md
Labels: 3: Reviews Complete

#954 Update README.md
  operations/research-and-development/product/technical-writing-team-handbook/README.md
Labels: 3: Reviews Complete

#955 Update README.md
  SUMMARY.md
  operations/research-and-development/product/technical-writing-team-handbook/README.md
  operations/research-and-development/product/technical-writing-team-handbook/work-with-us.md
  operations/research-and-development/product/technical-writing-team-handbook/writing-community-documentation.md
  operations/research-and-development/product/technical-writing-team-handbook/writing-feature-documentation.md
Labels: 3: Reviews Complete
