Repository mattermost/mattermost-handbook, pull requests merged in 2022-08, with the labels that each got.

#1058 Past mattercon details add
  contributors/mattercon/README.md
Labels: 3: Reviews Complete

#1062 Update release-overview.md
  operations/research-and-development/product/release-process/release-overview.md
Labels: 3: Reviews Complete

#1064 Update the AORs of DevOps team
  operations/research-and-development/organization/release_devops.md
Labels: 3: Reviews Complete

#1070 Added Desktop app translations owner
  contributors/join-us/localization.md
Labels: 2: Editor Review

#1068 New total rewards page
  SUMMARY.md
  operations/workplace/people/total-rewards.md
Labels: 2: Editor Review

#1061 Update how-to-spend-company-money.md
  operations/finance/staff-member-expenses/how-to-spend-company-money.md
Labels: 1: SME Review

#1055 Update steps for creating a redirect for in-product docs
  operations/research-and-development/product/product-management-team-handbook/README.md
Labels: 2: Editor Review

#1074 Update family-and-friends-day.md
  operations/workplace/people/working-at-mattermost/paid-time-off/family-and-friends-day.md
Labels: 3: Reviews Complete

#1073 Update total-rewards.md
  operations/workplace/people/total-rewards.md
Labels: 3: Reviews Complete

#1075 Update product-ownership-areas.md
  operations/research-and-development/product/product-management-team-handbook/README.md
  operations/research-and-development/product/product-management-team-handbook/pm-onboarding.md
  operations/research-and-development/product/product-management-team-handbook/product-ownership-areas.md
Labels: 3: Reviews Complete
