Repository mattermost/mattermost-handbook, pull requests merged in 2022-04, with the labels that each got.

#1014 Adding FAQ on EE contributions
  contributors/contributors/ways-to-contribute/README.md
Labels: 3: Reviews Complete

#1010 New QA Handbook page
  .gitbook/assets/rainforest_image1.png
  .gitbook/assets/rainforest_image10.png
  .gitbook/assets/rainforest_image11.png
  .gitbook/assets/rainforest_image12.png
  .gitbook/assets/rainforest_image13.png
  .gitbook/assets/rainforest_image14.png
  .gitbook/assets/rainforest_image15.png
  .gitbook/assets/rainforest_image16.png
  .gitbook/assets/rainforest_image17.png
  .gitbook/assets/rainforest_image18.png
  .gitbook/assets/rainforest_image19.png
  .gitbook/assets/rainforest_image2.png
  .gitbook/assets/rainforest_image20.png
  .gitbook/assets/rainforest_image21.png
  .gitbook/assets/rainforest_image22.png
  .gitbook/assets/rainforest_image23.png
  .gitbook/assets/rainforest_image24.png
  .gitbook/assets/rainforest_image25.png
  .gitbook/assets/rainforest_image26.png
  .gitbook/assets/rainforest_image27.png
  .gitbook/assets/rainforest_image28.png
  .gitbook/assets/rainforest_image29.png
  .gitbook/assets/rainforest_image3.png
  .gitbook/assets/rainforest_image30.png
  .gitbook/assets/rainforest_image31.png
  .gitbook/assets/rainforest_image32.png
  .gitbook/assets/rainforest_image33.png
  .gitbook/assets/rainforest_image34.png
  .gitbook/assets/rainforest_image35.png
  .gitbook/assets/rainforest_image36.png
  .gitbook/assets/rainforest_image37.png
  .gitbook/assets/rainforest_image38.png
  .gitbook/assets/rainforest_image4.png
  .gitbook/assets/rainforest_image5.png
  .gitbook/assets/rainforest_image6.png
  .gitbook/assets/rainforest_image7.png
  .gitbook/assets/rainforest_image8.png
  .gitbook/assets/rainforest_image9.png
  SUMMARY.md
  operations/research-and-development/quality/rainforest-process.md
Labels: 3: Reviews Complete

#1009 Update staff-recruiting.md
  contributors/join-us/staff-recruiting.md
Labels: 3: Reviews Complete

#1027 Add gifting policy to handbook
  SUMMARY.md
  operations/finance/staff-member-expenses/gifting-policy.md
Labels: 1: SME Review

#1004 Adding example on email
  operations/operations/README.md
Labels: 2: Editor Review

#1021 Update README.md
  contributors/join-us/README.md
Labels: 3: Reviews Complete
