Repository mattermost/mattermost-handbook, pull requests merged in 2022-05, with the labels that each got.

#1032 Added Elad to this page
  operations/finance/README.md
Labels: 1: SME Review

#1034 Update midyear-performance-review-timeline-2020.md
  operations/workplace/people/performance-reviews-50/midyear-performance-review-timeline-2020.md
Labels: 1: SME Review

#1017 Update how-to-procure-a-vendor-contract.md
  operations/finance/purchasing/how-to-procure-a-vendor-contract.md
Labels: 1: SME Review

#1037 Update cloud fast-forward process
  operations/research-and-development/product/release-process/release-overview.md
Labels: 3: Reviews Complete

#1038 Update Jira ticket guidelines
  operations/research-and-development/product/development-process/new-bug-tickets/README.md
Labels: 3: Reviews Complete

#1040 Add PM team list to handbook
  operations/research-and-development/product/product-management-team-handbook/README.md
Labels: 2: Editor Review

#1041 Update README.md
  operations/workplace/people/working-at-mattermost/travel/README.md
Labels: 1: SME Review
