Repository mattermost/mattermost-handbook, pull requests merged in 2023-06, with the labels that each got.

#1222 Add clear CTAs at the top of partner program page
  operations/sales/partner-programs.md
Labels: 3: Reviews Complete

#1224 Update marketing roster
  operations/messaging-and-math/README.md
Labels: 2: Editor Review

#1223 Update people-compliance.md
  operations/workplace/people/people-compliance.md
Labels: 3: Reviews Complete

#1228 Update people-compliance.md
  operations/workplace/people/people-compliance.md
Labels: 3: Reviews Complete

#1229 Update desktop-release.md
  operations/research-and-development/product/release-process/desktop-release.md
Labels: 3: Reviews Complete

#1230 Update family-and-friends-day.md
  operations/workplace/people/working-at-mattermost/paid-time-off/family-and-friends-day.md
Labels: 1: SME Review

#1233 Update hr-cadences.md
  operations/workplace/people/hr-cadences.md
Labels: 3: Reviews Complete

#1234 Update hr-cadences.md
  operations/workplace/people/hr-cadences.md
Labels: 3: Reviews Complete

#1226 Add Deployment Engineering to our handbook
  .gitbook/assets/post-sales-solutions-workflow.png
  .gitbook/assets/post-sales-support-workflow.png
  SUMMARY.md
  operations/deployment-engineering/README.md
  operations/deployment-engineering/frequently-asked-questions.md
  operations/deployment-engineering/overview.md
  operations/deployment-engineering/playbook-mme-sev1-outages.md
  operations/deployment-engineering/status-update-template.md
  operations/deployment-engineering/workflows.md
  operations/operations/README.md
Labels: 3: Reviews Complete
