Repository mattermost/mattermost-handbook, pull requests merged in 2023-04, with the labels that each got.

#1196 [GH-1105] - WIP - Documentation style guide revision
  .DS_Store
  .gitignore
  SUMMARY.md
  operations/.DS_Store
  operations/research-and-development/product/.DS_Store
  operations/research-and-development/product/technical-writing-team-handbook/documentation-style-guide.md
  operations/research-and-development/product/technical-writing-team-handbook/using-markdown.md
  operations/research-and-development/product/technical-writing-team-handbook/using-restructured-text.md
Labels: 3: Reviews Complete

#1200 Legal resources AOR update
  operations/legal/legal.md
Labels: 2: Editor Review

#1201 Clarified contribution eligibility and checkins
  contributors/join-us/github-sponsorship.md
Labels: 2: Editor Review

#1203 Adding a section in the handbook for where to share feedback
  operations/research-and-development/product/product-planning/feature-requests.md
Labels: 3: Reviews Complete

#1198 Add the product vulnerability process
  operations/security/product-security/product-vulnerability-process.md
Labels: Department/Engineering

#1206 Adding permissions for shipped languages
  contributors/join-us/localization.md
Labels: 2: Editor Review

#1192 Update release process docs
  SUMMARY.md
  operations/research-and-development/product/release-process/cloud-release.md
  operations/research-and-development/product/release-process/desktop-release.md
  operations/research-and-development/product/release-process/dot-release.md
  operations/research-and-development/product/release-process/feature-release.md
  operations/research-and-development/product/release-process/mobile-release.md
  operations/research-and-development/product/release-process/playbooks-release.md
  operations/research-and-development/product/release-process/release-overview.md
  operations/research-and-development/product/release-process/security-release.md
Labels: 3: Reviews Complete

#1207 Remove duplicate item in product vuln doc
  operations/security/product-security/product-vulnerability-process.md
Labels: 2: Editor Review
