Repository mattermost/mattermost-handbook, pull requests merged in 2023-10, with the labels that each got.

#1282 Update how-to-submit-a-purchase-request.md
  operations/finance/purchasing/airbase/how-to-submit-a-purchase-request.md
Labels: 3: Reviews Complete

#1284 Update delivery.md
  operations/research-and-development/organization/delivery.md
Labels: 3: Reviews Complete

#1285 Update how-to-submit-a-purchase-request.md
  operations/finance/purchasing/airbase/how-to-submit-a-purchase-request.md
Labels: 2: Editor Review

#1288 SecOps Team Roster Update
  operations/security/README.md
Labels: 3: Reviews Complete

#1286 Update README.md
  operations/finance/README.md
Labels: 2: Editor Review

#1273 Update company-agreements.md
  operations/operations/company-processes/company-agreements.md
Labels: 2: Editor Review

#1272 Update issue-solution.md
  operations/operations/company-processes/issue-solution.md
Labels: 3: Reviews Complete

#1271 Update company-cadence.md
  operations/operations/company-cadence.md
Labels: 3: Reviews Complete

#1270 Update community-response-policy.md
  operations/operations/company-policies/community-response-policy.md
Labels: 3: Reviews Complete

#1269 Update README.md
  operations/operations/company-metrics/README.md
Labels: 3: Reviews Complete

#1268 Update README.md
  operations/operations/mlt-cadence/README.md
Labels: 3: Reviews Complete

#1267 Update README.md
  README.md
Labels: 3: Reviews Complete

#1266 Update README.md
  company/about-mattermost/README.md
Labels: 3: Reviews Complete

#1263 Create directly-responsible-individuals.md
  operations/operations/directly-responsible-individuals.md
Labels: 1: SME Review
