Repository mattermost/mattermost-handbook, pull requests merged in 2023-01, with the labels that each got.

#1158 Update release overview
  operations/research-and-development/product/release-process/release-overview.md
Labels: 3: Reviews Complete

#1160 Surfacing config settings in search results
  operations/research-and-development/product/technical-writing-team-handbook/documentation-style-guide.md
Labels: 3: Reviews Complete

#1164 Add travel FAQs to 'how to spend company money' section
  operations/finance/staff-member-expenses/how-to-spend-company-money.md
Labels: 3: Reviews Complete

#1163 Update Links for UserVoice with Productboard
  contributors/contributors/guidelines/community-playbook.md
  contributors/contributors/guidelines/social-engagement-guidelines.md
  contributors/contributors/ways-to-contribute/README.md
  operations/research-and-development/product/product-management-team-handbook/pm-onboarding.md
Labels: 2: Editor Review

#1143 Create product-design-ownership-area
  operations/research-and-development/product/product-design-team-handbook/product-design-ownership-areas.md
Labels: Lifecycle/1:stale

#1166 Create contribution-events.md
  SUMMARY.md
  contributors/archive/README.md
  contributors/archive/hacktoberfest2021.md
  contributors/archive/hacktoberfest2022.md
  contributors/contributors/contribution-events.md
Labels: 1: SME Review

#1165 Add policy for core contributor expanded access
  SUMMARY.md
  operations/research-and-development/engineering/core-contributor-expanded-access.md
Labels: 3: Reviews Complete

#1162 Minor updates to CWP policies
  contributors/contributors/ways-to-contribute/community-content-program.md
Labels: 1: SME Review
