Repository mattermost/mattermost-handbook, pull requests merged in 2023-05, with the labels that each got.

#1210 Document R&D Calendar
  .gitbook/assets/rnd-calendar-accepted.png
  .gitbook/assets/rnd-calendar-invite.png
  .gitbook/assets/rnd-calendar-not-yet-accepted.png
  operations/research-and-development/organization/README.md
Labels: 3: Reviews Complete

#1209 Update instructions for labeling Jira tickets + Update translations PR reviewers
  contributors/join-us/localization.md
  operations/research-and-development/product/development-process/new-bug-tickets/README.md
Labels: 3: Reviews Complete

#1186 Update how-to-spend-company-money.md
  operations/finance/staff-member-expenses/how-to-spend-company-money.md
Labels: 3: Reviews Complete

#1175 Update README.md
  operations/operations/mlt-cadence/README.md
Labels: 3: Reviews Complete

#1213 Updated HR team list and DRIs
  operations/workplace/people/README.md
Labels: 1: SME Review

#1065 Minor updates to business model page, include self-serve description
  company/about-mattermost/business-model.md
Labels: 2: Editor Review, 3: Reviews Complete

#1218 Update R&D product org docs
  operations/research-and-development/README.md
  operations/research-and-development/organization/README.md
  operations/research-and-development/organization/core1.md
  operations/research-and-development/organization/core2.md
  operations/research-and-development/organization/growth.md
  operations/research-and-development/organization/integrations_framework.md
  operations/research-and-development/organization/qa.md
  operations/research-and-development/organization/self-serve_subscriptions.md
  operations/research-and-development/organization/server.md
  operations/research-and-development/organization/web_desktop_mobile.md
Labels: 3: Reviews Complete
